import type { HomeData } from './homeTypes'

/** Datos de muestra para /preview (revisión de diseño sin login). */
export const SAMPLE_HOME: HomeData = {
  displayName: 'Ernesto',
  reading: {
    bookId: 'sample',
    title: 'La Biblioteca de la Medianoche',
    author: 'Matt Haig',
    coverUrl: null,
    chapterNumber: 18,
    chapterLabel: 'El tablero de ajedrez',
    totalChapters: 73,
    percent: 25,
  },
  stats: { ideas: 12, replies: 34, finished: 3 },
  openPoll: { id: 'poll', title: 'Libro de agosto' },
  conversations: [
    {
      bookId: 'sample',
      bookTitle: 'La Biblioteca de la Medianoche',
      author: 'Matt Haig',
      upTo: 18,
      count: 12,
      avatars: ['Marina Ruiz', 'Carla Vega', 'Ola Prieto'],
      extra: 8,
    },
    {
      bookId: 'sample2',
      bookTitle: 'Proyecto Hail Mary',
      author: 'Andy Weir',
      upTo: 8,
      count: 8,
      avatars: ['Ander Gil', 'Rosa Mateo', 'Iván Sol'],
      extra: 5,
    },
    {
      bookId: 'sample3',
      bookTitle: 'Dune',
      author: 'Frank Herbert',
      upTo: 5,
      count: 6,
      avatars: ['Nuria Paz', 'Pau Roig'],
      extra: 3,
    },
  ],
  discover: [
    { id: 'd1', title: 'Stoner', author: 'John Williams' },
    { id: 'd2', title: 'Los detectives salvajes', author: 'Roberto Bolaño' },
    { id: 'd3', title: 'La casa de hojas', author: 'Mark Z. Danielewski' },
    { id: 'd4', title: 'Piranesi', author: 'Susanna Clarke' },
    { id: 'd5', title: 'El infinito en un junco', author: 'Irene Vallejo' },
  ],
  feed: [
    {
      id: '1',
      type: 'idea',
      authorName: 'Alba Ferrer',
      authorId: 'a',
      bookId: 'sample',
      bookTitle: 'La Biblioteca de la Medianoche',
      chapterNumber: 8,
      chapterLabel: 'Antimateria',
      kind: 'theory',
      body: 'La biblioteca no es un lugar: creo que cada estantería es una decisión que Nora no tomó. Fijaos en cómo la describe la señora Elm.',
      isClub: true,
      createdAt: 'hace 2 h',
      commentCount: 3,
      replies: [
        {
          id: 'r1',
          authorId: 'b',
          authorName: 'Carmen Ruiz',
          body: 'Ojo también al reloj parado a las 00:00, no puede ser casual.',
          unlockChapter: 8,
          createdAt: 'hace 1 h',
        },
        {
          id: 'r2',
          authorId: 'z',
          authorName: 'Pau Roig',
          body: null,
          unlockChapter: 40,
          createdAt: 'hace 20 min',
        },
      ],
      reactions: { '❤️': 4, '🔥': 2, '💡': 1 },
      myReaction: '❤️',
    },
    {
      id: '2',
      type: 'idea',
      authorName: 'Chas Molina',
      authorId: 'c',
      bookId: 'sample',
      bookTitle: 'La Biblioteca de la Medianoche',
      chapterNumber: 11,
      chapterLabel: 'La biblioteca de la medianoche',
      kind: 'question',
      body: '¿Alguien más se ha parado en la cita inicial? Creo que resume el libro entero.',
      isClub: false,
      createdAt: 'hace 40 min',
      commentCount: 1,
      replies: [],
      reactions: { '💡': 3 },
      myReaction: null,
    },
    {
      id: '3',
      type: 'post',
      postTitle: 'Por qué releo en verano',
      authorName: 'Carmen Ruiz',
      authorId: 'b',
      kind: null,
      body: 'Hay libros que solo funcionan con calor y horas largas. Este año repito tres, y uno es el del club.',
      isClub: true,
      createdAt: 'ayer',
      commentCount: 0,
      replies: [],
      reactions: {},
      myReaction: null,
    },
    {
      id: '4',
      type: 'idea',
      authorName: 'Pau Roig',
      authorId: 'z',
      bookId: 'sample',
      bookTitle: 'La Biblioteca de la Medianoche',
      chapterNumber: 41,
      chapterLabel: null,
      kind: 'theory',
      body: null,
      isClub: true,
      createdAt: 'hace 5 min',
      commentCount: 0,
      replies: [],
      reactions: {},
      myReaction: null,
    },
  ],
}
