import type { HomeData } from './homeTypes'

/** Datos de muestra para /preview (revisión de diseño sin login). */
export const SAMPLE_HOME: HomeData = {
  displayName: 'Ernesto',
  myId: 'e',
  readings: [
    {
      bookId: 'sample',
      title: 'La Biblioteca de la Medianoche',
      author: 'Matt Haig',
      coverUrl: null,
      chapterNumber: 18,
      chapterLabel: 'El tablero de ajedrez',
      totalChapters: 73,
      percent: 25,
    },
    {
      bookId: 'stoner',
      title: 'Stoner',
      author: 'John Williams',
      coverUrl: null,
      chapterNumber: 5,
      chapterLabel: null,
      totalChapters: 17,
      percent: 29,
    },
  ],
  readingBookIds: ['sample', 'stoner'],
  finishedBookIds: ['humanos'],
  stats: { ideas: 12, replies: 34, finished: 3 },
  openPoll: { id: 'poll', title: 'Libro de agosto' },
  conversations: [
    {
      bookId: 'sample',
      bookTitle: 'La Biblioteca de la Medianoche',
      author: 'Matt Haig',
      upTo: 18,
      count: 12,
      avatars: [
        { name: 'Marina Ruiz' },
        { name: 'Carla Vega' },
        { name: 'Ola Prieto' },
      ],
      extra: 8,
    },
  ],
  discover: [
    { id: 'd1', title: 'Stoner', author: 'John Williams' },
    { id: 'd2', title: 'Los detectives salvajes', author: 'Roberto Bolaño' },
    { id: 'd3', title: 'Piranesi', author: 'Susanna Clarke' },
  ],
  feed: [
    // Una IDEA (publicación principal)
    {
      id: '1',
      type: 'idea',
      authorName: 'Carlos H. Calcines',
      authorUsername: 'carlos',
      authorId: 'c',
      bookId: 'sample',
      bookTitle: 'La Biblioteca de la Medianoche',
      chapterNumber: 32,
      chapterLabel: 'Svalbard',
      kind: 'question',
      body: 'Totalmente inesperada la aparición de Hugo. ¿Qué creéis que aportará a la historia?',
      isClub: true,
      createdAt: 'hace 21 h',
      commentCount: 4,
      reactions: { '❤️': 2, '💡': 1 },
      myReaction: null,
      replies: [
        {
          id: 'n1',
          authorId: 'e',
          authorName: 'Ernesto Pérez',
          authorUsername: 'ernesto',
          body: 'Ya verás: creo que Hugo es la pieza que le faltaba al tablero.',
          unlockChapter: 32,
          createdAt: 'hace 13 h',
        },
        {
          id: 'n2',
          authorId: 'z',
          authorName: 'Pau Roig',
          authorUsername: 'pau',
          body: null,
          unlockChapter: 41,
          createdAt: 'hace 5 h',
        },
      ],
    },
    // Un HILO cuyo padre no está en el feed: cita + respuestas colgando
    {
      id: 'thread-9',
      type: 'reply',
      authorName: 'Carmen Ruiz',
      authorUsername: 'carmen',
      authorId: 'b',
      body: null,
      isClub: false,
      createdAt: 'hace 3 h',
      parent: {
        discussionId: '9',
        authorName: 'Marina Vidal',
        authorUsername: 'marina',
        body: '¿Nadie va a hablar del gato? Voltaire merece su propio club de fans.',
        chapterNumber: 6,
        chapterLabel: 'Puertas',
        bookTitle: 'La Biblioteca de la Medianoche',
        bookId: 'sample',
      },
      replies: [
        {
          id: 'n3',
          authorId: 'b',
          authorName: 'Carmen Ruiz',
          authorUsername: 'carmen',
          body: 'Presidenta del club de fans de Voltaire, aquí firmo.',
          unlockChapter: 6,
          createdAt: 'hace 3 h',
        },
      ],
    },
    // Una IDEA sobre una lectura personal (fuera del club)
    {
      id: '2',
      type: 'idea',
      authorName: 'Ernesto Pérez',
      authorUsername: 'ernesto',
      authorId: 'e',
      bookId: 'stoner',
      bookTitle: 'Stoner',
      chapterNumber: 5,
      chapterLabel: null,
      kind: 'comment',
      body: 'Nadie me avisó de que este libro «tranquilo» iba a dolerme tanto. La escena de la biblioteca con Edith es demoledora.',
      isClub: false,
      createdAt: 'hace 2 h',
      commentCount: 0,
      reactions: { '❤️': 1 },
      myReaction: null,
      replies: [],
    },
    // Una entrada de MURO
    {
      id: '3',
      type: 'post',
      postTitle: 'Por qué releo en verano',
      authorName: 'Carmen Ruiz',
      authorUsername: 'carmen',
      authorId: 'b',
      kind: null,
      body: 'Hay libros que solo funcionan con calor y horas largas. Este año repito tres, y uno es el del club.',
      isClub: true,
      createdAt: 'ayer',
    },
  ],
}
