import type { HomeData } from './homeTypes'

/** Datos de muestra para /preview (revisión de diseño sin login). */
export const SAMPLE_HOME: HomeData = {
  displayName: 'Ernesto',
  myId: 'e',
  reading: {
    bookId: 'sample',
    title: 'La Biblioteca de la Medianoche',
    author: 'Matt Haig',
    coverUrl: null,
    chapterNumber: 18,
    chapterLabel: 'El tablero de ajedrez',
    totalChapters: 73,
    percent: 25,
  },
  stats: { ideas: 12, replies: 34, finished: 3 },
  openPoll: { id: 'poll', title: 'Libro de agosto' },
  conversations: [
    {
      bookId: 'sample',
      bookTitle: 'La Biblioteca de la Medianoche',
      author: 'Matt Haig',
      upTo: 18,
      count: 12,
      avatars: ['Marina Ruiz', 'Carla Vega', 'Ola Prieto'],
      extra: 8,
    },
  ],
  discover: [
    { id: 'd1', title: 'Stoner', author: 'John Williams' },
    { id: 'd2', title: 'Los detectives salvajes', author: 'Roberto Bolaño' },
    { id: 'd3', title: 'Piranesi', author: 'Susanna Clarke' },
  ],
  feed: [
    // Una IDEA (publicación principal)
    {
      id: '1',
      type: 'idea',
      authorName: 'Carlos H. Calcines',
      authorUsername: 'carlos',
      authorId: 'c',
      bookId: 'sample',
      bookTitle: 'La Biblioteca de la Medianoche',
      chapterNumber: 32,
      chapterLabel: 'Svalbard',
      kind: 'question',
      body: 'Totalmente inesperada la aparición de Hugo. ¿Qué creéis que aportará a la historia?',
      isClub: true,
      createdAt: 'hace 21 h',
      commentCount: 1,
      reactions: { '❤️': 2, '💡': 1 },
      myReaction: null,
    },
    // Una RESPUESTA (con el mensaje padre citado encima)
    {
      id: 'r1',
      type: 'reply',
      authorName: 'Ernesto Pérez',
      authorUsername: 'ernesto',
      authorId: 'e',
      chapterNumber: 32,
      body: 'Ya verás: creo que Hugo es la pieza que le faltaba al tablero. Ojo a cómo habla del tiempo.',
      isClub: false,
      createdAt: 'hace 13 h',
      parent: {
        discussionId: '1',
        authorName: 'Carlos H. Calcines',
        authorUsername: 'carlos',
        body: 'Totalmente inesperada la aparición de Hugo. ¿Qué creéis que aportará a la historia?',
        chapterNumber: 32,
        chapterLabel: 'Svalbard',
        bookTitle: 'La Biblioteca de la Medianoche',
      },
    },
    // Una respuesta BLOQUEADA (su autor iba por delante)
    {
      id: 'r2',
      type: 'reply',
      authorName: 'Pau Roig',
      authorUsername: 'pau',
      authorId: 'z',
      chapterNumber: 41,
      body: null,
      isClub: false,
      createdAt: 'hace 5 h',
      parent: {
        discussionId: '1',
        authorName: 'Carlos H. Calcines',
        authorUsername: 'carlos',
        body: 'Totalmente inesperada la aparición de Hugo. ¿Qué creéis que aportará a la historia?',
        chapterNumber: 32,
        chapterLabel: 'Svalbard',
        bookTitle: 'La Biblioteca de la Medianoche',
      },
    },
    // Una entrada de MURO
    {
      id: '3',
      type: 'post',
      postTitle: 'Por qué releo en verano',
      authorName: 'Carmen Ruiz',
      authorUsername: 'carmen',
      authorId: 'b',
      kind: null,
      body: 'Hay libros que solo funcionan con calor y horas largas. Este año repito tres, y uno es el del club.',
      isClub: true,
      createdAt: 'ayer',
    },
  ],
}
